### ISSUE TITLE
正文提取规则求助

### ISSUE THREAD

**Issue by xikjun** [kunl/wiz#3]
Hi：有几点不明白求教
1 “正文之前的HTML文字”是啥作用。看例子是给提取的正文加样式吗？是从哪里提取的？
2 http://old.sebug.net/paper/python/ch04.html#s01   这个网页把横线上下横线间的内容提取出来咋个写规则？

谢谢
**j.xik@163.com**

**Comment by kunl** [comment]
这个我尝试过了，没有成功。网站的排版太简单了，不能提取出个性化的内容。

**Comment by xikjun** [comment]
谢谢！我用Python做了一个脚本，删除不要的标签，这下导出的资料清爽了肖军-------- 原始邮件 --------主题：Re: [wiz] 正文提取规则求助 (#3)发件人：忆年 收件人：kunl/wiz 抄送：xikjun 这个我尝试过了，没有成功。网站的排版太简单了，不能提取出个性化的内容。

**Comment by kunl** [comment]
求分享
